language: node_js
dist: xenial
node_js:
    - 10
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
        recipients:
            - ci@ngqp.io
script:
    - commitlint-travis
    - yarn run lint
    - yarn run core:build
    - yarn run core:test
    - yarn run demo:build:prod
    - yarn run api-docs:build
after_success:
    - yarn run codecov
