language: node_js
dist: trusty
node_js:
    - lts/*
notifications:
    email:
        on_success: change
        on_failure: always
        recipients:
            - ci@ngqp.io
script:
    - yarn run lint
    - yarn run core:build
    - yarn run demo:build:prod
    - yarn run api-docs:build